TRIPLET_ENGINE_X11_LIBS = -lTripleT_Engine_X11 -lX11 

VULKAN_LIBRARY_PATH ?=
ifneq ($(strip $(VULKAN_LIBRARY_PATH)),)
	TRIPLET_ENGINE_X11_LIBS += -L$(VULKAN_LIBRARY_PATH)
endif

TRIPLET_ENGINE_X11_LIBS += -lvulkan
